main.go, metric_publish/publish.go, scripts/etc/tsdb.ini
not tested yet. but compiles :)
also @woodsaj can you give me push access to this repo.
=> use kafka for publishing metrics

scripts/package.sh
should fix https://github.com/raintank/ops/issues/387
=> make package declare it replaces tsdb

metric_publish/publish.go
see https://github.com/Shopify/sarama/pull/790
=> the latest version of sarama requires config.Producer.Return.Success to be set

circle.yml, event_publish/publish.go, main.go, metric_publish/publish.go, scripts/config/tsdb.ini, scripts/depends.sh
We now support partitioning byOrg or bySeries.  bySeries is the new default.
=> refactor partitioning to use cluster.KafkaPartitioner

circle.yml, event_publish/publish.go, main.go, metric_publish/publish.go, scripts/config/tsdb.ini, util/buffer_pool.go
- clean up config settings.  Moved the configs for event_publisher
and metric_publisher to their respective packages.
- add tunables for kafka flush duration and max messages.
=> performance improvements

graphite/graphite.go, main.go, scripts/config/tsdb.ini
Also limit the hack to GET requests.
fixes #45
=> only enable worldpingHack if worldpingUrl is set

carbon/carbon.go, carbon/schemas.go, carbon/schemas_test.go
feel free to be as harsh on this PR as i've been on the tagging PR ;-)
=> Misc post carbon tagging

metric_publish/publish.go, scripts/config/tsdb.ini
=> fix deadlock when queue.buffering.max.messages is reached

auth/gcom/auth.go, auth/gcom/auth_test.go, auth/gcom/roles.go
- update URL to try and fetch specific hosted-metrics instance by id
- fix bugs that caused successfull auth for invalid instance ids.
- add unit tests for instance auth
=> bug fixes in instanceAuth

api/middleware.go, cmd/cortex-gw/main.go, vendor/vendor.json
Also add the vendor file. I blame librdkafka messing up the vendor
folder causing the oversight.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/raintank/tsdb-gw/82)
=> Make use of a different server for prom metrics.

cmd/cortex-gw/main.go
This will fix the broken scrapes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/raintank/tsdb-gw/85)
=> Listen for metrics on all interfaces by default

cmd/cortex-gw/main.go, publish/cortex/publish.go, query/cortex/cortex.go, scripts/config/cortex-gw.ini
@Dieterbe I closed my last PR this one is more in line with what we are looking for given your suggestions.
=> refactor flags in package file

api/middleware.go, api/models/context.go, cmd/tsdb-gw/main.go, query/graphite/graphite.go, query/graphite/validators.go, scripts/config/tsdb-gw.ini, vendor/github.com/go-macaron/binding/LICENSE, vendor/github.com/go-macaron/binding/README.md, vendor/github.com/go-macaron/binding/binding.go, vendor/github.com/go-macaron/binding/errors.go, vendor/gopkg.in/macaron.v1/README.md, vendor/gopkg.in/macaron.v1/context.go, vendor/gopkg.in/macaron.v1/logger.go, vendor/gopkg.in/macaron.v1/macaron.go, vendor/gopkg.in/macaron.v1/response_writer.go, vendor/gopkg.in/macaron.v1/router.go, vendor/gopkg.in/macaron.v1/tree.go, vendor/gopkg.in/macaron.v1/util_go17.go, vendor/gopkg.in/macaron.v1/util_go18.go, vendor/vendor.json
Not tested yet, going to test it. Also needed to update the macaron dependency to make the validator not blow up
=> [WIP] filter by timerange

publish/cortex/publish.go
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>
=> Customise the number of connections to each host

Gopkg.lock, Gopkg.toml, vendor/github.com/grafana/metrictank/conf/indexrules.go, vendor/github.com/grafana/metrictank/conf/init.go
set metrictank dep to use the master branch. It was pinned to
the bump-logrus branch which doesnt exist anymore
=> fix metrictank deps

auth/gcom/auth.go, auth/gcom/auth_test.go, auth/gcom/roles.go
Signed-off-by: Jacob Lisi <jacob.t.lisi@gmail.com>
=> enforce auth-valid-instance-type when flag is set

auth/gcom/auth.go, auth/gcom/auth_test.go, auth/gcom/cache.go
Fixes: https://github.com/raintank/tsdb-gw/issues/142
=> Fix race by removing global variable

ingest/metrics.go, ingest/metrics_response.go
see #121 
see https://github.com/graphite-ng/carbon-relay-ng/pull/338 for corresponding crng PR
=> issue 121: don't reject ingestion requests upon invalid data

auth/gcom/auth.go, auth/gcom/auth_test.go, auth/gcom/roles.go
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>
=> auth: Add ability to validate cluster name

api/api_test.go
Adding tests for websockets which would help make sure any newly added middlewares pass these test
=> Unit tests for websockets

README.md
@jtlisi can you fill in the persister-gw part and @woodsaj can you do the auth part
intention is not to have very rich documentation - cause it's bound to get out of date anyway, but at least document the most important things
=> slightly better readme

ingest/rate_limit_test.go
This fixes some race conditions in unit tests
=> Fix race condition in tests

ingest/rate_limit_test.go
better explanation in unit test
=> add comment

Gopkg.lock, publish/kafka/publish.go, vendor/github.com/grafana/metrictank/cluster/partitioner/partitioner.go, vendor/github.com/grafana/metrictank/schema/partition.go, vendor/github.com/grafana/metrictank/util/fnv32a.go, vendor/github.com/grafana/metrictank/util/fnv64a.go
related: https://github.com/grafana/metrictank/pull/1444
=> Support bySeriesWithTagsFnv
