raintank/tsdb-gw

api/metrics.go

Some customers are still sending V0 metrics. When decoded into
a schema.V1 metric the metric.Mtype will be empty and the metric.Metric
may also be empty. These fields need to be populated to pass validation.

accpet raintank/schema.V0 metrics

---

api/api.go
api/metrictank.go
main.go
metrictank/metrictank.go

directly proxy requests on `/metrics/delete` to the metrictank
endpoint, bypassing graphite-api.
fixes #21 
example:
```
mst@ubuntu:~$ curl  -H 'X-Org-Id: 1' 'http://localhost/metrics/delete' --form 'query=some.id.of.a.metric.1'
{"deletedDefs":1}
mst@ubuntu:~$ curl  -H 'X-Org-Id: 1' 'http://localhost/metrics/delete' --form 'query=some.id.of.a.metric.1'
{"deletedDefs":0}
```

proxy delete endpoint to metrictank

---

api/graphite.go
graphite/graphite.go

The transport to the backends is a member of `ReverseProxy`, so it would be better if we could reuse them instead of reinstantiating on each request.
I tested in the QA env and i can still push metrics via carbon-relay-ng and query them from Grafana.

Reuse reverse proxies instead of reinstantiating

---

api/api.go
api/metrics.go
api/middleware.go
event_publish/publish.go
main.go
metric_publish/publish.go

use raintank/metrictank/stats library to send stats directly to graphite.  Statsd is flaky in our hosted-metrics platform, with the tsdb-gw where tsdb-gw services just randomly stop sending metrics.
use a logHandler from the gorillatookit to write apache common log format logs of http requests to stdout

Stats and logs

---

api/middleware.go

in particular, all 5xx responses should have an error log.
now they all do.

log error when Auth check fails

---

api/middleware.go
circle.yml
cmd/tsdb-usage/main.go
cmd/tsdb-usage/stats.go
main.go
metric_publish/publish.go
scripts/Dockerfile
scripts/build.sh
scripts/build_docker.sh
scripts/config/tsdb.ini
scripts/depends.sh
scripts/entrypoint.sh
scripts/package.sh
usage/usage.go
usage/usage_test.go
vendor/github.com/golang/glog/LICENSE
vendor/github.com/golang/glog/README
vendor/github.com/golang/glog/glog.go
vendor/github.com/golang/glog/glog_file.go
vendor/vendor.json

- created separate tsdb-usage binary that accepts and aggregates
usage data from 1 or more tsdb-gw servers.  Each org has their
own usage metrics and these metrics are fed into metrictank
via kafka.
- the metrics collected are
- hosted-metrics.usage.active_series : unique number of series seen in previous 6hours
- hosted-metrics.usage.datapoints_per_minute : rate of metrics received
- hosted-metrics.usage.api.request.`<path>`.status.`<status>` : api request counts by response status.

add usage reporting

---

cmd/tsdb-usage/main.go

because we never try and write to connections, if we dont set a
readDeadline we will never notice that a connection is dead and
so the connection will never be closed.

SetReadDeadline on connections to tsdb-gw. fixes #53

---

api/api.go
api/metrictank.go
metrictank/metrictank.go

This PR proxies requests for index.json directly to MT, bypassing graphite-web.
I added support for querying `/metrics/index.json` in addition to `/graphite/metrics.json` since people seem to do that a lot.
Not sure if we want to also support `/metrics/find` (and/or hijack `/graphite/metrics/find` or all of `/graphite/metrics`) though now that would be fairly easy.

proxy /metrics/index.json and /graphite/metrics/index.json directly to MT

---

metric_publish/publish.go

This improves the performance by a lot
Explanation of the screenshot:
- Up until 18:10 it running the old tsdb-gw with sarama
- At 18:10 I switched it to the `0.8.0` and the metric publishing time exploded
- 18:26 I deployed this branch with default settings and performance improved
- 18:31 I've increased the `metrics-buffer-max-ms` setting to `1000` and performance looked about the same like with Sarama

tune send buffer

---

api/api.go
api/prometheus.go

This adds the proxy to push requests for Prometheus queries to Metrictank

add prometheus proxy

---

api/api.go
api/middleware.go
auth/auth.go
auth/grafana_com_instance.go
cmd/cortex-gw/main.go
cmd/tsdb-gw/main.go
ingest/carbon/carbon.go
ingest/carbon/schemas.go
ingest/datadog.go
ingest/ingest.go
ingest/opentsdb.go
ingest/prometheus.go
publish/cortex/proxy.go
publish/cortex/publish.go
publish/cortex/publish_test.go
publish/kafka/publish.go
publish/kafka/schemas.go
publish/publish.go
query/cortex/cortex.go
scripts/config/cortex-gw.ini
vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go
vendor/golang.org/x/net/context/ctxhttp/ctxhttp_pre17.go
vendor/vendor.json

this adds a publisher pipeline for cortex so datadog/opentsdb/etc can be written to cortex.
* `.` characters are replaced wholesale on write with `_`
* The publish code could benefit from a metrics queue and some rate limiting features. I'd rather keep it simple at the moment and add performance optimizing features as needed.

cortex publish interface

---

cmd/tsdb-gw/main.go
cmd/tsdb-usage/main.go
publish/kafka/publish.go

because it generates all metrics by itself with known interval.
technically, tsdb-gw also only needs a storage-schemas.conf if we have input plugins enabled that don't enforce/know an interval (e.g. if only kafka input is enabled, we don't need it)
, but adding those conditionals to the code seems clumsy and fragile.

tsdb-usage doesn't need storage-schemas.conf

---

api/middleware.go
ingest/carbon/carbon.go
ingest/metrics.go
publish/kafka/publish.go
vendor/github.com/grafana/metrictank/stats/counterrate32.go

because we like to aggregate across instances.
this makes that easier

expose counters as rates as well

---

cmd/tsdb-gw/main.go
vendor/github.com/grafana/metrictank/stats/out_graphite.go
vendor/vendor.json

also adds a config parameter to tsdb, which allows to define the write timeout

update vendored graphite stats output

---

api/middleware.go

Cortex uses different buckets as the gw which causes differences in the histogram numbers.

Use the same buckets as underlying services

---

.circleci/config.yml
auth/file.go
cmd/tsdb-usage/stats.go
publish/kafka/publish.go
query/graphite/graphite.go
scripts/config/tsdb-gw.ini

from  https://github.com/Shopify/sarama/blob/v1.19.0/config.go#L324-L330
```
The version of Kafka that Sarama will assume it is running against.
Defaults to the oldest supported stable version. Since Kafka provides
backwards-compatibility, setting it to a version older than you have
will not break anything, although it may prevent you from using the
latest features. Setting it to a version greater than you are actually
running may lead to random breakage.
```

Sarama kafka version

---

Gopkg.lock
api/api.go
auth/auth.go
auth/file.go
auth/gcom/auth.go
auth/gcom/auth_test.go
auth/gcom/cache.go
auth/grafana-com.go
auth/grafana_com_instance.go
scripts/config/cortex-gw.ini
scripts/config/tsdb-gw.ini
vendor/golang.org/x/sync/AUTHORS
vendor/golang.org/x/sync/CONTRIBUTORS
vendor/golang.org/x/sync/LICENSE
vendor/golang.org/x/sync/PATENTS
vendor/golang.org/x/sync/singleflight/singleflight.go

Updating entries in the cache has been made async. This ensures that
1) requests are not blocked waiting for re-validation of tokens and
instances
2) we dont get into situations where we flood grafana.com with
validation requests
Instead of updating the cached entries when they are past their TTL,
We run a background tasks that scans over the cached items looking
for expired entries and re-validating them.
On reads of the cache, we update a lastRead timer.  If this timer
falls behind the last validation then we know that the cached item
is no longer being read, so we purge it from the cache.
To handle the background tasks, the AuthPlugin interface has been updated
to ensure plugins have a "Stop()" method.
Finally the auth-valid-ttl and auth-invalid-ttl cmdline args have been
replaced with …

refactor token and instance caches. fixes #130

---

publish/cortex/proxy.go
publish/cortex/publish.go

This fixes the bad load-balancing. Adds some latency but literally better than before.
See: https://github.com/raintank/tsdb-gw/pull/126#issuecomment-434011531

Disable persistent connections

---

api/middleware.go

To support websockets with reverse proxy, response writer needs to satisfy `http.Hijacker` interface.
Added this method to `TracingResponseWriter` which in turn calls underlying Hijack method implemented by `macaron.ResponseWriter`
This is needed to support live tailing of logs from loki

Add support for websockets

---

cmd/tsdb-gw/main.go

The cumulative counts for each bucket make aggregating the latencies
possible, and allow us to get the aggregated 99th percentile latency
across many clusters.
The metrics will be collected as "cortex_gw_request_duration" instead of "tsdb_gw_request_duration", but that is deliberate to take advantage of the existing recording_rules we already have in place.

collect prometheus histrograms for graphite request latencies

---

cmd/tsdb-gw/main.go
ingest/mt_bulk_importer.go

this adds an optional endpoint to tsdb-gw which can be used to bulk import data into metrictank's backend store

add endpoint for mt bulk importer

---

Gopkg.lock
auth/gcom/auth.go
auth/gcom/auth_test.go
publish/kafka/publish.go
publish/kafka/publish_test.go
util/flags.go
util/flags_test.go
vendor/github.com/Shopify/sarama/mocks/async_producer.go
vendor/github.com/Shopify/sarama/mocks/consumer.go
vendor/github.com/Shopify/sarama/mocks/mocks.go
vendor/github.com/Shopify/sarama/mocks/sync_producer.go

Support publishing to multiple Kafka topics with restriction by org id:
- in the Kafka publisher: options "metrics-topic" and "metrics-partition-scheme" were amended to support multiple comma separated values; they remain backwards compatible
- in the Kafka publisher: a new option "only-org-id" was added which restricts which data get sent to each Kafka topic depending on the data's org id. An empty value or 0 means unrestricted
- a completion of vendored sarama was necessary to access the mocks for testing
- Int64SliceFlag was moved to the util package to allow reuse

Support publishing to multiple Kafka topics with restriction by org id

---

publish/kafka/publish.go
publish/kafka/publish_test.go

Added option 'discard-prefixes' that discards data points of series starting with the given prefixes.
This is needed during instance migrations so that the target instance does not receive metrics that are internal/specific to the source instance such as:
`tsdb-gw.stats.local-cluster-10-cassandra.tsdb-10-byseries-32-cassandra-55fdd66b98-86xwq`
`metrictank.stats.local-cluster-10-cassandra.mt-read00-10-byseries-32-cassandra-a-758966f4c8-8lk76`

 Added option 'discard-prefixes' that discards data points of series starting with the given prefixes

---

Gopkg.lock
vendor/github.com/grafana/metrictank/schema/metric.go

The udpated code from Metrictank now uses the EatDots
function which will clean up bad metric names.
Validate() is already called on all ingested metrics before
they are sent to be published, so the code will already be
in use.

update vendored metrictank

---

Gopkg.lock
Gopkg.toml
api/limits_test.go
api/middleware.go
cmd/tsdb-gw/main.go
ingest/metrics.go
ingest/rate_limit.go
ingest/rate_limit_test.go
vendor/golang.org/x/time/AUTHORS
vendor/golang.org/x/time/CONTRIBUTORS
vendor/golang.org/x/time/LICENSE
vendor/golang.org/x/time/PATENTS
vendor/golang.org/x/time/rate/rate.go

Related #134
I'm not sure what to do if a single request contains more datapoints than the secondly budget. 
I'd assume that this is a case that shouldn't happen unless we limit a user to an extremely low rate, or a user configures their crng to a huge batch size.
I think we could enforce something like a max batch size by responding with 429 if the received batch has more datapoints than the configured secondly rate. If a user does receive 429s they'd then have to configure their crng's max-batch-size.

add optional rate limiter

---

publish/kafka/publish.go
publish/kafka/publish_test.go

New flag "rewrite-org-id" allowing `orgId` to be rewritten when published to Kafka.
This will be useful in instance migrations where the orgId is already used.
Can be specified once for each Kafka topic.
For example:
`--rewrite-org-id=33:45,1:10` will rewrite `orgId` for all incoming `MetricData` with `orgId` `33` to `45`, and the ones with `orgId` `1` to `10`. 
Some light refactoring was necessary, in particular isolating the marshaling of `MetricData`.
Fixes #197

New flag "rewrite-org-id" allowing orgId to be rewritten when published to Kafka
